/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jswave;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import jswave.js.JsEnv;
import jswave.js.Script;

/**
 *
 * @author lenovo
 */
public class JsWaveJFrame extends javax.swing.JFrame {

    /**
     * Creates new form jsWaveJFrame
     */
    public JsWaveJFrame() {
        initComponents();
        initSciprt();
        initKey();
    }

    JsEnv jsEnv;
    
    private void initSciprt() {
        Script script = Script.getScript();
        script.setPanel(waveJPanel);
        
        
        
        jsEnv = new JsEnv();
        jsEnv.loadFile("default.js");
        jsEnv.invokeFunction("main");
        
        waveJPanel.setTimeRange(0, 8100000);
    }

    private void initKey() {
        addKeyListener(new KeyListener() { 
            @Override 
            public void keyTyped(KeyEvent e) { 
            } 
 
            @Override 
            public void keyPressed(KeyEvent e) { 
                String keyText = KeyEvent.getKeyText(e.getKeyCode()); 
                if (!e.isActionKey()) { 
                    if (keyText.equals("W")) {
                        waveJPanel.scalerUp();
                    }
                    else if (keyText.equals("S")) {
                        waveJPanel.scalerDown();
                    }
                    else if (keyText.equals("A")) {
                        waveJPanel.moveLeft();
                    }
                    else if (keyText.equals("D")) {
                        waveJPanel.moveRight();
                    }
                    else if (keyText.equals("Q")) {
                        
                    }
                    else if (keyText.equals("E")) {
                        
                    }
                } 
            } 
 
            @Override 
            public void keyReleased(KeyEvent e) { 

            } 
 
        });         
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        waveJPanel = new jswave.ui.WaveJPanel();
        jMenuBarMain = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuOpen = new javax.swing.JMenu();
        jMenuEdit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout waveJPanelLayout = new javax.swing.GroupLayout(waveJPanel);
        waveJPanel.setLayout(waveJPanelLayout);
        waveJPanelLayout.setHorizontalGroup(
            waveJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        waveJPanelLayout.setVerticalGroup(
            waveJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        jMenuBarMain.setFont(jMenuBarMain.getFont());

        jMenuFile.setText("File");
        jMenuFile.setFont(jMenuFile.getFont());
        jMenuFile.setHideActionText(true);

        jMenuOpen.setText("Open");
        jMenuFile.add(jMenuOpen);

        jMenuBarMain.add(jMenuFile);

        jMenuEdit.setText("Edit");
        jMenuEdit.setFont(jMenuEdit.getFont());
        jMenuBarMain.add(jMenuEdit);

        setJMenuBar(jMenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(waveJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(waveJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JsWaveJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JsWaveJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JsWaveJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JsWaveJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JsWaveJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuOpen;
    private jswave.ui.WaveJPanel waveJPanel;
    // End of variables declaration//GEN-END:variables
}
